spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql : true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sns?serverTimezone=Asia/Seoul
#    username: root
#    password: 'xcz119'
#    data: classpath:/data.sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.cctpabcwfz7d.ap-northeast-2.rds.amazonaws.com:3306/sns?serverTimezone=Asia/Seoul
    username: admin
    password: 'rlaejrdn12'
    data: classpath:/data.sql
#    initialization-mode: always





jwt:
  key: $rocket12345123451234512345123451234512345123451234512345
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
