spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql : true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=Asia/Seoul
    username: root
    password: 'xcz119'
    data: classpath:/data.sql
#    initialization-mode: always
cloud:
  aws:
    credentials:
      access-key: AKIAXDXAYIJX3YNIYLGZ
      secret-key: r1d+oX+Q5B0G0GLmdgoda/0FrGbQDYigxRO6HYo/pOM=
    s3:
      bucket: mywebboard.com
    region:
      static: ap-northeast-2
    stack:
      auto: false
jwt:
  key: $rocket12345123451234512345123451234512345123451234512345
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
