##spring:
##  h2:
##    console:
##      enabled: true
##      path: /h2
##  datasource:
##    url: jdbc:h2:mem:test
##  jpa:
##    hibernate:
##      ddl-auto: create  # (1) ??? ?? ??
##    show-sql: true      # (2) SQL ?? ??
##    properties:
##      hibernate:
##        format_sql: true  # (3) SQL pretty print
##  sql:
##    init:
##      data-locations: classpath*:db/h2/data.sql.
##logging:
##  level:
##    org:
##      springframework:
##        orm:
##          jpa: DEBUG
##server:
##  servlet:
##    encoding:
##      force-response: true
#
#spring:
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      ddl-auto: create
#    show-sql: true
#    properties.hibernate.format_sql : true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:8080/sns?serverTimezone=Asia/Seoul
#    username: root
#    password: 'wl257max25s!MAX@'
##    initialization-mode: always
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
#jwt:
#  key: $rocket12345123451234512345123451234512345123451234512345
#  access-token-expiration-minutes: 30
#  refresh-token-expiration-minutes: 420
#
## mysql로 수정필요
#
### TEST용 임시 정보
##mail:
##  address:
##    admin: admin@gmail.com
##
##jwt:
##  key: $rocket12345123451234512345123451234512345123451234512345 #${JWT_SECRET_KEY}           # 민감한 정보는 시스템 환경 변수에서 로드한다.
##  access-token-expiration-minutes: 60
##  refresh-token-expiration-minutes: 420