spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql : true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: db-url
    username: name
    password: password
#    initialization-mode: always
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
jwt:
  key : {$secret-Key}
  access-token-expiration-minutes: Min
  refresh-token-expiration-minutes: Min
cloud:
  aws:
    credentials:
      access-key: ${s3.accesskey}
      secret-key: ${s3.secretkey}
    region:
      static: ${s3.resion}
    s3:
      bucket: ${s3.bucket}
    stack:
      auto: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
